### ISSUE TITLE
CI/CD pipeline

### ISSUE THREAD

**Issue by Staneesh** [Staneesh/shamir-py#4]
We should have a CI/CD pipeline that will automatically lint the code we commit and run tests. This will prevent us from merging code that does not pass tests into main branch. @aleks111222 What do you think? Do you want to set that up?

**Comment by aleks111222** [comment]
Yeah, sounds great, i thought about it also, pipelines arw a crucial part of a good ci/cd ecosystem. If you know how to do it, go ahead.

**Comment by Staneesh** [comment]
Done, closing 🌞 🌴
